name: gbif-species-trainer-AMI-fork
channels:
  - defaults
  - pytorch
  - anaconda
dependencies:
  - python=3.9
  - torchvision
  - pytorch
  - opencv
  - matplotlib
  - numpy
  - pip
  - scikit-learn
  - pandas
  - keras
  - pandas
  - keras
  - pre-commit
  - tqdm
  - wandb
  - webdataset
  - python-dwca-reader
  - tensorflow
  - pip:
    - pygbif
    - torchsummary
    - timm
