wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685453009.046088
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 23
      4: 3.9.16
      5: 0.15.3
      8:
      - 5
