wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1667258214.714601
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      2:
      - 1
      - 2
      - 3
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 23
      - 24
      4: 3.9.13
      5: 0.13.4
      8:
      - 5
